#JReleaser 1.23.0
#Sat Apr 18 01:55:01 CEST 2026
commitFullHash=69d00f42dd380c0cf255e976443d36987412c594
commitShortHash=69d00f4
javaVendor=Oracle Corporation
javaVersion=25
javaVmVersion=25+37-LTS-jvmci-b01
milestoneName=v1.5.1
platform=osx-aarch_64
platformReplaced=osx-aarch_64
previousTagName=v1.5.1-pre-tamboui
projectName=skills
projectSnapshot=false
projectVersion=1.5.1
projectVersionMajor=1
projectVersionMinor=5
projectVersionNumber=1.5.1
projectVersionPatch=1
releaseBranch=main
releaseName=v1.5.1
tagName=v1.5.1
timestamp=2026-04-18T01\:55\:01.270954+02\:00
